steps:
  - name: node:16
    id: install
    entrypoint: npm
    args: ['install']
    waitFor: ['-']

  - name: node:16
    entrypoint: npm
    args: ['test']
    waitFor: ['install']

  - name: 'gcr.io/kaniko-project/executor:v1.6.0'
    args: ['--destination=gcr.io/$PROJECT_ID/elastic-buildkite-pr-bot:$COMMIT_SHA', '--cache=true']
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'elastic-buildkite-pr-bot',
        '--image',
        'gcr.io/$PROJECT_ID/elastic-buildkite-pr-bot:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--service-account',
        'elastic-buildkite-pr-bot@elastic-ci-prod.iam.gserviceaccount.com',
        '--allow-unauthenticated',
        '--concurrency',
        '80',
        '--max-instances',
        '1',
        '--set-env-vars',
        'NODE_ENV=production,BOOTSTRAP_GCP_SECRETS=true,LOG_TO_CONSOLE=true,SECRETS_PROJECT_ID=543704608146,BUILDKITE_ORG=elastic,GCP_SECRET_PREFIX=elastic-buildkite-pr-bot,ENABLE_ES_CLOUD=true,ORG_WIDE_CONFIGS=elastic/pr-bot-config-test',
      ]
